version: 2.1

jobs:
  build:
    working_directory: ~/dp/data-pipeline-flink
    docker:
      - image: 'maven:3-openjdk-8'
    steps:
      - checkout:
          path: ~/dp
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: build & test
          command: mvn clean scoverage:report
      - persist_to_workspace:
          root: ~/
          paths:
            - dp/data-pipeline-flink
  sonar:
    docker:
      - image: 'maven:3-openjdk-11'
    steps:
      - checkout:
          path: ~/dp
      - attach_workspace:
          at: .
      - run:
          name: sonar
          command: |
            cd ~/project/dp/data-pipeline-flink && mvn -X sonar:sonar -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=harshavardhanc_sunbird-data-pipeline -Dsonar.organization=harshavardhanc -Dsonar.exclusions=~/project/dp/ansible/**,~/project/dp/schema/**,~/project/dp/pipelines/**,~/project/dp/data-pipeline/**,~/project/dp/kubernetes/**,~/project/dp/test-data/**, -Dsonar.host.url=https://sonarcloud.io -Dsonar.scala.coverage.reportPaths=~/project/dp/data-pipeline-flink/target/scoverage.xml


workflows:
  main:
    jobs:
      - build
      - sonar:
          requires:
            - build
